<?php

function mymodule_menu(){
    // path location (<a href="http://www.url.com/foo/bar" title="http://www.url.com/foo/bar">http://www.url.com/foo/bar</a> )
    $items['foo/bar'] = array(
        // page title
        'title' => 'Page Title',
        // describe the page for the menu system.  site visitors will not see this
        'description' => 'Simple custom hook_menu() implementation.',
        // function that is called when visiting the new path
        'page callback' => 'my_page_function',
        // permissions required to view page
        'access arguments' => array('access content'),
    );  
    return $items;
}

/*
 * Returns custom content to Drupal
 */
function my_page_function(){
  // Call theme() function, so that Drupal includes the custom-page.tpl.php template
    $result = db_insert('ignorelist')
          ->fields(array(
              instance_id => "ghfkhdkhdkhgdkgjh"
            ))
          ->execute();
    echo json_encode(array('success'=>$result));die;
  return theme('my_custom_template');
}
   
